# Generated by Django 4.0.3 on 2022-04-02 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignmentAPI', '0006_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('numberOfHours', models.PositiveIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignmentAPI.career')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignmentAPI.department')),
                ('studyPlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignmentAPI.studyplan')),
            ],
        ),
        migrations.AlterModelOptions(
            name='snippet',
            options={},
        ),
        migrations.CreateModel(
            name='TeachingPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfHours', models.PositiveIntegerField()),
                ('numberOfGroups', models.PositiveIntegerField()),
                ('classType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachingAssignmentAPI.classtype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignmentAPI.subject')),
                ('yearPeriod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachingAssignmentAPI.yearperiod')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=1)),
                ('group', models.IntegerField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignmentAPI.professor')),
                ('teachingPlanning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignmentAPI.teachingplanning')),
            ],
        ),
    ]
