# Generated by Django 4.0.3 on 2022-04-11 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignmentAPI',
         '0007_subject_alter_snippet_options_teachingplanning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarmenTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignmentAPI.schoolyear')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignmentAPI.semester')),
                ('yearPeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignmentAPI.yearperiod')),
            ],
        ),
    ]
