# Generated by Django 4.0.3 on 2022-04-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignmentAPI', '0008_semester_carmentable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeachingPlanning',
            new_name='SubjectDescription',
        ),
        migrations.RenameModel(
            old_name='SchoolYear',
            new_name='TeachingGroup',
        ),
        migrations.RenameModel(
            old_name='YearPeriod',
            new_name='TimePeriod',
        ),
        migrations.RenameField(
            model_name='carmentable',
            old_name='schoolYear',
            new_name='teachingGroup',
        ),
        migrations.RenameField(
            model_name='carmentable',
            old_name='yearPeriod',
            new_name='timePeriod',
        ),
        migrations.RenameField(
            model_name='subjectdescription',
            old_name='yearPeriod',
            new_name='timePeriod',
        ),
        migrations.RenameField(
            model_name='teachingassignment',
            old_name='teachingPlanning',
            new_name='subjectDescription',
        ),
    ]
