# Generated by Django 4.0.3 on 2022-04-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignmentAPI', '0010_alter_teachinggroup_studyplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachinggroup',
            old_name='studyPlan',
            new_name='study_plan',
        ),
    ]
