# Generated by Django 4.0.3 on 2022-04-25 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignmentAPI', '0011_rename_studyplan_teachinggroup_study_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmentable',
            old_name='teachingGroup',
            new_name='teaching_group',
        ),
        migrations.RenameField(
            model_name='carmentable',
            old_name='timePeriod',
            new_name='time_period',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='scientificDegree',
            new_name='scientific_degree',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='teachingCategory',
            new_name='teaching_category',
        ),
        migrations.RenameField(
            model_name='studyplan',
            old_name='numberOfSemesters',
            new_name='number_of_semesters',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='numberOfHours',
            new_name='number_of_hours',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='studyPlan',
            new_name='study_plan',
        ),
        migrations.RenameField(
            model_name='subjectdescription',
            old_name='classType',
            new_name='class_type',
        ),
        migrations.RenameField(
            model_name='subjectdescription',
            old_name='numberOfGroups',
            new_name='number_of_groups',
        ),
        migrations.RenameField(
            model_name='subjectdescription',
            old_name='numberOfHours',
            new_name='number_of_hours',
        ),
        migrations.RenameField(
            model_name='subjectdescription',
            old_name='timePeriod',
            new_name='time_period',
        ),
        migrations.RenameField(
            model_name='teachingassignment',
            old_name='subjectDescription',
            new_name='subject_description',
        ),
        migrations.AlterField(
            model_name='teachinggroup',
            name='study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_groups', to='teachingAssignmentAPI.studyplan'),
        ),
    ]
