# Generated by Django 4.0.3 on 2022-04-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignmentAPI',
         '0012_rename_teachinggroup_carmentable_teaching_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='owner',
        ),
    ]
