# Generated by Django 4.0.3 on 2022-05-05 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignmentAPI', '0013_remove_career_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmentable',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignmentAPI.semester'),
        ),
        migrations.AlterField(
            model_name='carmentable',
            name='teaching_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignmentAPI.teachinggroup'),
        ),
        migrations.AlterField(
            model_name='carmentable',
            name='time_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignmentAPI.timeperiod'),
        ),
        migrations.AlterField(
            model_name='department',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachingAssignmentAPI.career'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignmentAPI.department'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='scientific_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignmentAPI.scientificdegree'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='teaching_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignmentAPI.teachingcategory'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignmentAPI.career'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignmentAPI.department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='study_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignmentAPI.studyplan'),
        ),
        migrations.AlterField(
            model_name='subjectdescription',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachingAssignmentAPI.classtype'),
        ),
        migrations.AlterField(
            model_name='subjectdescription',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignmentAPI.subject'),
        ),
        migrations.AlterField(
            model_name='subjectdescription',
            name='time_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachingAssignmentAPI.timeperiod'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignmentAPI.professor'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='subject_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignmentAPI.subjectdescription'),
        ),
        migrations.AlterField(
            model_name='teachinggroup',
            name='study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_groups', to='teachingAssignmentAPI.studyplan'),
        ),
    ]
