# Generated by Django 4.0.3 on 2022-03-30 02:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignment.department')),
            ],
        ),
        migrations.CreateModel(
            name='ScientificDegree',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('since', models.DateField()),
                ('until', models.DateField(blank=True, null=True)),
                ('numberOfSemesters', models.SmallIntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('numberOfHours', models.PositiveIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('StudyPlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignment.studyplan')),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignment.career')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignment.department')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingCategory',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearPeriod',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingPlanning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('numberOfHours', models.PositiveIntegerField()),
                ('numberOfGroups', models.PositiveIntegerField()),
                ('classType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachingAssignment.classtype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignment.subject')),
                ('yearPeriod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachingAssignment.yearperiod')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssigment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('percent', models.IntegerField(default=1)),
                ('group', models.IntegerField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignment.professor')),
                ('teachingPlanning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignment.teachingplanning')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('studyPlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachingAssignment.studyplan')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='scientificDegree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignment.scientificdegree'),
        ),
        migrations.AddField(
            model_name='professor',
            name='teachingCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignment.teachingcategory'),
        ),
    ]
