# Generated by Django 4.0.3 on 2022-07-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0014_alter_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdescription',
            name='string_repr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
