# Generated by Django 4.0.3 on 2022-07-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0015_subjectdescription_string_repr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectdescription',
            name='string_repr',
        ),
    ]
