# Generated by Django 4.0.3 on 2022-08-02 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0016_remove_subjectdescription_string_repr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cotutors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotutors', to='teachingAssignment.professor')),
                ('tutors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='teachingAssignment.professor')),
            ],
        ),
    ]
