# Generated by Django 4.0.3 on 2022-08-03 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0017_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cotutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotutor', to='teachingAssignment.professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignment.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='teachingAssignment.professor')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='teachingAssignment.professor')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='teachingAssignment.professor')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignment.thesis')),
            ],
        ),
    ]
