# Generated by Django 4.0.3 on 2022-08-02 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0017_student_thesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='teachingAssignment.professor')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='teachingAssignment.professor')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignment.thesis')),
            ],
        ),
    ]
