# Generated by Django 4.0.3 on 2022-08-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0017_student_thesis_thesiscommittee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachinggroup',
            name='study_plan',
        ),
    ]
