# Generated by Django 4.0.3 on 2022-08-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0018_thesiscommittee'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesiscommittee',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
