# Generated by Django 4.0.3 on 2022-08-03 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0018_thesis_thesiscommittee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='student',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
