# Generated by Django 4.0.3 on 2022-08-04 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0018_remove_teachinggroup_study_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarmenTable',
        ),
    ]
