# Generated by Django 4.0.3 on 2022-08-03 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0019_remove_thesis_student_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesiscommittee',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='thesiscommittee',
            name='secretary',
        ),
        migrations.RemoveField(
            model_name='thesiscommittee',
            name='thesis',
        ),
        migrations.DeleteModel(
            name='Thesis',
        ),
        migrations.DeleteModel(
            name='ThesisCommittee',
        ),
    ]
