# Generated by Django 4.0.3 on 2022-08-05 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0020_carmentable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarmenTable',
        ),
    ]
