# Generated by Django 4.0.3 on 2022-08-05 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0022_carmentable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_hours', models.PositiveIntegerField()),
                ('number_of_groups', models.PositiveIntegerField()),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachingAssignment.classtype')),
                ('scholar_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignment.carmentable')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignment.subject')),
                ('time_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachingAssignment.timeperiod')),
            ],
        ),
        migrations.DeleteModel(
            name='TeachingAssignment',
        ),
    ]
