# Generated by Django 4.0.3 on 2022-08-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0025_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='career',
        ),
    ]
