# Generated by Django 4.0.3 on 2022-08-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0027_career_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='faculty',
        ),
    ]
