# Generated by Django 4.0.3 on 2022-08-06 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0029_career_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachingAssignment.faculty'),
        ),
    ]
