# Generated by Django 4.0.3 on 2022-08-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0031_remove_department_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='teachingAssignment.faculty'),
        ),
    ]
