# Generated by Django 4.0.3 on 2022-08-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0033_alter_department_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_assignments', models.ManyToManyField(to='teachingAssignment.teachingassignment')),
            ],
        ),
    ]
