# Generated by Django 4.0.3 on 2022-08-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0035_remove_professor_created_remove_professor_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='created',
        ),
    ]
