# Generated by Django 4.0.3 on 2022-08-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0036_remove_career_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
