# Generated by Django 4.0.3 on 2022-10-14 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0038_remove_thesis_cotutor_remove_thesis_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectdescription',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignment.classtype'),
        ),
        migrations.AlterField(
            model_name='subjectdescription',
            name='time_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingAssignment.timeperiod'),
        ),
    ]
