# Generated by Django 4.0.3 on 2022-10-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0039_alter_subjectdescription_class_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectdescription',
            name='scholar_year',
        ),
    ]
