# Generated by Django 4.0.3 on 2022-10-14 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0040_remove_subjectdescription_scholar_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdescription',
            name='teaching_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachingAssignment.teachinggroup'),
            preserve_default=False,
        ),
    ]
