# Generated by Django 4.0.3 on 2022-11-01 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0041_subjectdescription_teaching_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectdescription',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='teachingAssignment.subject'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='group',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='percent',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='professor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='teachingAssignment.professor'),
        ),
    ]
