# Generated by Django 4.0.3 on 2022-11-01 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0042_alter_subjectdescription_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingassignment',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachingAssignment.professor'),
        ),
    ]
