# Generated by Django 4.0.3 on 2022-11-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0043_alter_teachingassignment_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
