# Generated by Django 4.0.3 on 2022-11-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0043_alter_teachingassignment_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='opponent_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='president_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='secretary_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='teaching_load',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
