# Generated by Django 4.0.3 on 2022-11-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0044_scholaryear'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdescription',
            name='scholar_year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teachingAssignment.scholaryear'),
            preserve_default=False,
        ),
    ]
