# Generated by Django 4.0.3 on 2022-11-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0045_subjectdescription_scholar_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholaryear',
            name='current_year',
            field=models.BooleanField(default=False),
        ),
    ]
