# Generated by Django 4.0.3 on 2022-11-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0045_alter_professor_opponent_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='teaching_load',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
