# Generated by Django 4.0.3 on 2022-11-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0046_alter_professor_teaching_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='opponent_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='president_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='secretary_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
