# Generated by Django 4.0.3 on 2022-09-15 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachingAssignment', '0038_remove_thesis_cotutor_remove_thesis_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('student', models.CharField(max_length=200)),
                ('cotutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotutor', to='teachingAssignment.professor')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='teachingAssignment.professor')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='teachingAssignment.professor')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='thesisAssignment.place')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president', to='teachingAssignment.professor')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='teachingAssignment.professor')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesisAssignment.thesis')),
            ],
        ),
    ]
