# Generated by Django 4.0.3 on 2022-09-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0038_remove_thesis_cotutor_remove_thesis_student_and_more'),
        ('thesisAssignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='cotutors',
            field=models.ManyToManyField(blank=True, null=True, related_name='tutors', to='teachingAssignment.professor'),
        ),
    ]
