# Generated by Django 4.0.3 on 2022-09-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisAssignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesiscommittee',
            name='time',
        ),
        migrations.AlterField(
            model_name='thesiscommittee',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
