# Generated by Django 4.0.3 on 2022-09-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisAssignment', '0002_remove_thesiscommittee_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesiscommittee',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thesiscommittee',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
