# Generated by Django 4.0.3 on 2022-10-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesisAssignment', '0003_alter_thesis_cotutors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesiscommittee',
            name='date',
        ),
        migrations.RemoveField(
            model_name='thesiscommittee',
            name='place',
        ),
        migrations.RemoveField(
            model_name='thesiscommittee',
            name='time',
        ),
    ]
