# Generated by Django 4.0.3 on 2022-09-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0038_remove_thesis_cotutor_remove_thesis_student_and_more'),
        ('thesisAssignment', '0003_thesiscommittee_time_alter_thesiscommittee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='teachingAssignment.professor'),
        ),
    ]
