# Generated by Django 4.0.3 on 2022-09-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesisAssignment', '0004_alter_thesis_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesis',
            old_name='tutor',
            new_name='tutors',
        ),
    ]
