# Generated by Django 4.0.3 on 2022-10-15 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesisAssignment', '0004_remove_thesiscommittee_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisDefense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesisAssignment.place')),
                ('thesis_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesisAssignment.thesiscommittee')),
            ],
        ),
    ]
