# Generated by Django 4.0.3 on 2022-09-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0038_remove_thesis_cotutor_remove_thesis_student_and_more'),
        ('thesisAssignment', '0005_rename_tutor_thesis_tutors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='tutors',
        ),
        migrations.AddField(
            model_name='thesis',
            name='tutors',
            field=models.ManyToManyField(related_name='tutors', to='teachingAssignment.professor'),
        ),
    ]
