# Generated by Django 4.0.3 on 2022-09-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesisAssignment', '0006_remove_thesis_tutors_thesis_tutors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesis',
            old_name='tutors',
            new_name='cotutors',
        ),
        migrations.RenameField(
            model_name='thesis',
            old_name='cotutor',
            new_name='tutor',
        ),
    ]
