# Generated by Django 4.0.3 on 2022-11-01 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0043_alter_teachingassignment_group_and_more'),
        ('thesisAssignment', '0006_alter_thesisdefense_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesiscommittee',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='teachingAssignment.professor'),
        ),
        migrations.AlterField(
            model_name='thesiscommittee',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='president', to='teachingAssignment.professor'),
        ),
        migrations.AlterField(
            model_name='thesiscommittee',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='teachingAssignment.professor'),
        ),
    ]
