# Generated by Django 4.0.3 on 2022-11-09 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingAssignment', '0045_subjectdescription_scholar_year'),
        ('thesisAssignment', '0007_alter_thesiscommittee_opponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='scholar_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachingAssignment.scholaryear'),
            preserve_default=False,
        ),
    ]
